name: financialBigData_PradoAffolter
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - libffi=3.4.4
  - libgomp=13.2.0
  - openssl=3.2.0
  - pip=23.2.1
  - python=3.10.13
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
    - aiohttp==3.8.6
    - aiosignal==1.3.1
    - annotated-types==0.6.0
    - anyio==3.7.1
    - aplus==0.11.0
    - appdirs==1.4.4
    - arch==6.2.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - astropy==5.3.4
    - asttokens==2.4.0
    - async-lru==2.0.4
    - async-timeout==4.0.3
    - attrs==23.1.0
    - babel==2.12.1
    - backcall==0.2.0
    - beautifulsoup4==4.12.2
    - blake3==0.3.3
    - bleach==6.0.0
    - bokeh==3.3.0
    - bqplot==0.12.42
    - branca==0.6.0
    - cachetools==5.3.2
    - certifi==2023.7.22
    - cffi==1.15.1
    - charset-normalizer==3.2.0
    - click==8.1.7
    - cloudpickle==3.0.0
    - colorcet==3.0.1
    - comm==0.1.4
    - contourpy==1.2.0
    - cssselect==1.2.0
    - curl-cffi==0.5.10
    - cycler==0.12.1
    - cython==3.0.6
    - dadaptation==3.1
    - dask==2024.1.0
    - datatable==1.1.0
    - debugpy==1.8.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - distributed==2024.1.0
    - dpcpp-cpp-rt==2024.0.2
    - ecos==2.0.12
    - exceptiongroup==1.1.3
    - executing==1.2.0
    - fastapi==0.104.1
    - fastjsonschema==2.19.0
    - filelock==3.13.1
    - fonttools==4.46.0
    - fqdn==1.5.1
    - frozendict==2.3.10
    - frozenlist==1.4.0
    - fsspec==2023.12.1
    - future==0.18.3
    - google-search-results==2.4.2
    - git+https://github.com/mariostoev/finviz@bc02ca9bb980151c33fc7000276bbb0a0c729577
    - h11==0.14.0
    - h5py==3.10.0
    - hfhd==0.1.4
    - html5lib==1.1
    - httptools==0.6.1
    - idna==3.4
    - igraph==0.11.3
    - importlib-metadata==6.8.0
    - ipydatawidgets==4.3.5
    - ipykernel==6.25.2
    - ipyleaflet==0.17.4
    - ipympl==0.9.3
    - ipython==8.15.0
    - ipython-genutils==0.2.0
    - ipyvolume==0.6.3
    - ipyvue==1.10.1
    - ipyvuetify==1.8.10
    - ipywebrtc==0.6.0
    - ipywidgets==8.1.1
    - isoduration==20.11.0
    - jedi==0.19.0
    - jinja2==3.1.2
    - joblib==1.3.2
    - json5==0.9.14
    - jsonpointer==2.4
    - jsonschema==4.20.0
    - jsonschema-specifications==2023.11.2
    - jupyter==1.0.0
    - jupyter-client==8.3.1
    - jupyter-console==6.6.3
    - jupyter-core==5.3.1
    - jupyter-events==0.7.0
    - jupyter-lsp==2.2.0
    - jupyter-server==2.7.3
    - jupyter-server-terminals==0.4.4
    - jupyterlab==4.0.6
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.25.0
    - jupyterlab-widgets==3.0.9
    - kaleido==0.2.1
    - kiwisolver==1.4.5
    - lead-lag==2.3
    - llvmlite==0.41.1
    - locket==1.0.0
    - lxml==4.9.3
    - lz4==4.3.2
    - mako==1.3.0
    - markdown-it-py==3.0.0
    - markupsafe==2.1.3
    - matplotlib==3.8.2
    - matplotlib-inline==0.1.6
    - mdurl==0.1.2
    - mistune==3.0.1
    - mkl==2024.0.0
    - mkl-fft==1.3.6
    - mkl-random==1.2.2
    - mkl-service==2.4.0
    - mpmath==1.3.0
    - msgpack==1.0.7
    - multidict==6.0.4
    - multitasking==0.0.11
    - nbclient==0.8.0
    - nbconvert==7.8.0
    - nbformat==5.9.2
    - nest-asyncio==1.5.8
    - networkx==3.2.1
    - notebook==7.0.4
    - notebook-shim==0.2.3
    - numba==0.58.1
    - numexpr==2.9.0
    - numpy==1.24.4
    - outcome==1.3.0.post0
    - overrides==7.4.0
    - packaging==23.1
    - pandas==2.1.4
    - pandocfilters==1.5.0
    - param==2.0.1
    - parso==0.8.3
    - partd==1.4.1
    - patsy==0.5.4
    - peewee==3.17.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==10.1.0
    - platformdirs==3.10.0
    - plotly==5.18.0
    - powerlaw==1.5
    - prettytable==3.9.0
    - progressbar2==4.2.0
    - prometheus-client==0.17.1
    - prompt-toolkit==3.0.39
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==11.0.0
    - pycparser==2.21
    - pyct==0.5.0
    - pydantic==2.4.2
    - pydantic-core==2.10.1
    - pydot==1.4.2
    - pyerfa==2.0.1.1
    - pygments==2.16.1
    - pyopencl==2023.1.4
    - pyparsing==3.1.1
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - python-dotenv==1.0.0
    - python-igraph==0.11.3
    - python-json-logger==2.0.7
    - python-louvain==0.16
    - python-utils==3.8.1
    - pythreejs==2.4.2
    - pytools==2023.1.1
    - pytrends==4.9.2
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - pyzmq==25.1.1
    - qtconsole==5.4.4
    - qtpy==2.4.0
    - referencing==0.32.0
    - requests==2.31.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==13.6.0
    - rpds-py==0.13.2
    - rpy2==3.5.14
    - scikit-learn==1.3.2
    - scipy==1.11.4
    - seaborn==0.13.0
    - selenium==4.16.0
    - send2trash==1.8.2
    - six==1.16.0
    - sniffio==1.3.0
    - snowballstemmer==2.2.0
    - sortedcontainers==2.4.0
    - soupsieve==2.5
    - stack-data==0.6.2
    - starlette==0.27.0
    - statsmodels==0.14.0
    - tabulate==0.9.0
    - tbb==2021.11.0
    - tblib==3.0.0
    - tenacity==8.2.3
    - terminado==0.17.1
    - texttable==1.7.0
    - threadpoolctl==3.2.0
    - tinycss2==1.2.1
    - tomli==2.0.1
    - toolz==0.12.0
    - tornado==6.3.3
    - tqdm==4.66.1
    - traitlets==5.10.0
    - traittypes==0.2.1
    - trio==0.23.1
    - trio-websocket==0.11.1
    - typing-extensions==4.8.0
    - tzdata==2023.3
    - tzlocal==5.2
    - uri-template==1.3.0
    - urllib3==2.0.5
    - user-agent==0.1.10
    - uvicorn==0.23.2
    - vaex==4.17.0
    - vaex-astro==0.9.3
    - vaex-core==4.17.1
    - vaex-hdf5==0.14.1
    - vaex-jupyter==0.8.2
    - vaex-ml==0.18.3
    - vaex-server==0.9.0
    - vaex-viz==0.5.4
    - watchfiles==0.21.0
    - wcwidth==0.2.6
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.6.3
    - websockets==12.0
    - widgetsnbextension==4.0.9
    - win-inet-pton==1.1.0
    - window-ops==0.0.14
    - wsproto==1.2.0
    - xarray==2023.10.1
    - xyzservices==2023.10.1
    - yarl==1.9.2
    - yfinance==0.2.33
    - zict==3.0.0
    - zipp==3.17.0
